### ISSUE TITLE
Compatibility with non-UiBinder based GWT project

### ISSUE THREAD

**Issue by kerbymart** [ArcBees/gwt-seo#5]
Given that there are quite few popular frameworks for GWT which does not use GWT UiBinder explicitly, for example JBoss Errai framework which does not use UiBInder but a HTML-based templating then gwt-seo project should not just be for UiBInder, it should be used also in native GWT UI based project and HTML-based templating GWT project

**Comment by christiangoudreau** [comment]
It is :D You can use the java classes without UiBinder

**Comment by olafleur** [comment]
I think this issue should be closed. I don't have the rights. @jasonlemay ?

**Comment by kerbymart** [comment]
@christiangoudreau This should work with Errai templating :-)

**Comment by christiangoudreau** [comment]
Awesome, did you try?
